<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
<v t="amd.20150915153206.1"><vh>專案說明</vh>
<v t="amd.20150919102209.1" a="E"><vh>使用工具</vh>
<v t="amd.20150919112415.1"><vh>影片檔案</vh></v>
</v>
<v t="amd.20150919102541.1"><vh>pelican 與 Markdown</vh></v>
</v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20150919103428.1"><vh>reveal.js 設定</vh></v>
<v t="amd.20150919103341.1" a="E"><vh>Jupyter 設定</vh>
<v t="amd.20150919103923.1"><vh>設定檔案位置</vh></v>
<v t="amd.20150919104249.1"><vh>檢查 profile 位置</vh></v>
</v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
<v t="amd.20150919112710.1" a="E"><vh>@path pelican</vh>
<v t="amd.20150919113340.1"><vh>以下為與 pelican 有關的設定檔案</vh></v>
<v t="amd.20150919113132.1"><vh>@edit publishconf.py</vh></v>
</v>
</v>
<v t="amd.20150919113957.1"><vh>以下為 pelican 文章</vh></v>
<v t="amd.20150919124128.1"><vh>@button pelican content</vh></v>
<v t="amd.20150919114010.1" a="E"><vh>@path pelican\content</vh>
<v t="amd.20150919114035.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="harry.20151109110612.1"><vh>@edit 40323251_cp_w1&amp;2.md</vh></v>
<v t="harry.20151109112306.1"><vh>@edit 40323251_cp_w3.md</vh></v>
<v t="harry.20151109112314.1"><vh>@edit 40323251_cp_w4.md</vh></v>
<v t="harry.20151109112321.1"><vh>@edit 40323251_cp_w5.md</vh></v>
<v t="harry.20151109112329.1"><vh>@edit 40323251_cp_w6.md</vh></v>
<v t="harry.20151109112248.1"><vh>@edit 40323251_cp_w7.md</vh></v>
<v t="123.20160104033147.1"><vh>@edit 40323251_cp_w10.md</vh></v>
<v t="123.20160104033306.1"><vh>@edit 40323251_cp_w11.md</vh></v>
<v t="123.20160104033319.1"><vh>@edit 40323251_cp_w12.md</vh></v>
<v t="123.20160104033325.1"><vh>@edit 40323251_cp_w13.md</vh></v>
<v t="123.20160104033330.1"><vh>@edit 40323251_cp_w14.md</vh></v>
<v t="123.20160104033335.1"><vh>@edit 40323251_cp_w15.md</vh></v>
<v t="123.20160104033340.1"><vh>@edit 40323251_cp_w16.md</vh></v>
</v>
<v t="amd.20150919120205.1"><vh>以下為 reveal 投影片</vh></v>
<v t="amd.20150913233943.1"><vh>@clean cadpbw1.html</vh>
<v t="amd.20150913233943.2" a="E"><vh>html</vh>
<v t="amd.20150913233943.3" a="E"><vh>head</vh>
<v t="amd.20150913233943.4"><vh>title</vh></v>
</v>
<v t="amd.20150913233943.5" a="E"><vh>body</vh>
<v t="amd.20150913233943.6" a="E"><vh>div</vh>
<v t="amd.20150913233943.7" a="E"><vh>div</vh>
<v t="amd.20150913234947.1"><vh>title page</vh>
<v t="amd.20150913235225.1"><vh>標題頁下的子頁</vh></v>
</v>
<v t="amd.20150913235034.1"><vh>本日要點</vh></v>
<v t="amd.20150914000138.1"><vh>Anaconda Python</vh></v>
<v t="amd.20150914000332.1" a="E"><vh>設計的表達方式</vh>
<v t="amd.20150914000332.2"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="amd.20150913235123.1"><vh>結論</vh></v>
</v>
</v>
<v t="amd.20150913233943.81"><vh>script</vh></v>
<v t="amd.20150913233943.82"><vh>script</vh></v>
<v t="amd.20150913233943.83"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.1"><vh>@clean cadpaw1.html</vh>
<v t="amd.20150915155634.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915155634.3" a="E"><vh>head</vh>
<v t="amd.20150915155634.4"><vh>title - 標題</vh></v>
<v t="amd.20150915155634.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915155634.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915155634.8"><vh>body</vh>
<v t="amd.20150915155634.9" a="E"><vh>div - reveal</vh>
<v t="amd.20150915155634.10" a="E"><vh>div - slides</vh>
<v t="amd.20150915155634.11"><vh>h1 - 課程說明</vh></v>
<v t="amd.20150915172241.1"><vh>h1 - 開放自評規劃</vh></v>
<v t="amd.20150915155634.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="amd.20150915155634.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915155634.14"><vh>h2</vh></v>
<v t="amd.20150915155634.15"><vh>h2</vh></v>
<v t="amd.20150915155634.16"><vh>h2</vh></v>
</v>
<v t="amd.20150915173703.1"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915173703.2" a="E"><vh>pre</vh>
<v t="amd.20150915173703.3"><vh>code</vh></v>
</v>
<v t="amd.20150915173703.4"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.17"><vh>h2</vh></v>
<v t="amd.20150915204710.1"><vh>內嵌 Vimeo 影片</vh></v>
<v t="amd.20150915155634.18"><vh>h2</vh></v>
<v t="amd.20150915155634.19"><vh>h2</vh></v>
<v t="amd.20150915155634.20"><vh>markdown 頁面</vh></v>
<v t="amd.20150915155634.21" a="E"><vh>h2</vh>
<v t="amd.20150915160450.1"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915155634.28" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915161424.1"><vh>h2</vh></v>
<v t="amd.20150915155634.29"><vh>p</vh></v>
<v t="amd.20150915155634.30"><vh>p</vh></v>
<v t="amd.20150915155634.31"><vh>p</vh></v>
<v t="amd.20150915155634.32"><vh>p</vh></v>
<v t="amd.20150915155634.33"><vh>p</vh></v>
<v t="amd.20150915155634.34"><vh>p</vh></v>
<v t="amd.20150915155634.35"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915155634.36"><vh>h2</vh></v>
<v t="amd.20150915155634.37"><vh>p</vh>
<v t="amd.20150915155634.38"><vh>a</vh></v>
<v t="amd.20150915155634.39"><vh>a</vh></v>
<v t="amd.20150915155634.40"><vh>a</vh></v>
<v t="amd.20150915155634.41"><vh>a</vh></v>
<v t="amd.20150915155634.42"><vh>a</vh></v>
<v t="amd.20150915155634.43"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.44"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915155634.45" a="E"><vh>p</vh>
<v t="amd.20150915155634.46"><vh>a</vh></v>
<v t="amd.20150915155634.47"><vh>a</vh></v>
<v t="amd.20150915155634.48"><vh>a</vh></v>
<v t="amd.20150915155634.49"><vh>a</vh></v>
<v t="amd.20150915155634.50"><vh>a</vh></v>
<v t="amd.20150915155634.51"><vh>a</vh></v>
<v t="amd.20150915155634.52"><vh>a</vh></v>
<v t="amd.20150915155634.53"><vh>a</vh></v>
<v t="amd.20150915155634.54"><vh>a</vh></v>
<v t="amd.20150915155634.55"><vh>a</vh></v>
<v t="amd.20150915155634.56"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.57"><vh>h2</vh></v>
<v t="amd.20150915155634.58"><vh>p</vh>
<v t="amd.20150915155634.59"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.60"><vh>a</vh></v>
<v t="amd.20150915155634.61"><vh>h2</vh></v>
<v t="amd.20150915155634.62" a="E"><vh>pre</vh>
<v t="amd.20150915155634.63"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.64"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915155634.65" a="E"><vh>pre</vh>
<v t="amd.20150915155634.66"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.67" a="E"><vh>div</vh>
<v t="amd.20150915155634.68"><vh>h2</vh></v>
<v t="amd.20150915155634.69"><vh>pre</vh>
<v t="amd.20150915155634.70"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915155634.71"><vh>h2</vh></v>
<v t="amd.20150915155634.72"><vh>h2</vh></v>
<v t="amd.20150915155634.73"><vh>p</vh></v>
<v t="amd.20150915155634.74"><vh>pre</vh>
<v t="amd.20150915155634.75"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.76"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915155634.77"><vh>p</vh></v>
<v t="amd.20150915155634.78" a="E"><vh>pre</vh>
<v t="amd.20150915155634.79"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.80" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915155634.81" a="E"><vh>pre</vh>
<v t="amd.20150915155634.82"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.83"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.85"><vh>h2</vh></v>
<v t="amd.20150915155634.86" a="E"><vh>ul</vh>
<v t="amd.20150915155634.87"><vh>li</vh></v>
<v t="amd.20150915155634.88"><vh>li</vh></v>
<v t="amd.20150915155634.89"><vh>li</vh></v>
<v t="amd.20150915155634.90"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.91"><vh>h2</vh></v>
<v t="amd.20150915155634.92"><vh>ol</vh>
<v t="amd.20150915155634.93"><vh>li</vh></v>
<v t="amd.20150915155634.94"><vh>li</vh></v>
<v t="amd.20150915155634.95"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.96"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915155634.97" a="E"><vh>table</vh>
<v t="amd.20150915155634.98"><vh>thead</vh>
<v t="amd.20150915155634.99"><vh>tr</vh>
<v t="amd.20150915155634.100"><vh>th</vh></v>
<v t="amd.20150915155634.101"><vh>th</vh></v>
<v t="amd.20150915155634.102"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915155634.103"><vh>tbody</vh>
<v t="amd.20150915155634.104"><vh>tr</vh>
<v t="amd.20150915155634.105"><vh>td</vh></v>
<v t="amd.20150915155634.106"><vh>td</vh></v>
<v t="amd.20150915155634.107"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.108"><vh>tr</vh>
<v t="amd.20150915155634.109"><vh>td</vh></v>
<v t="amd.20150915155634.110"><vh>td</vh></v>
<v t="amd.20150915155634.111"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.112"><vh>tr</vh>
<v t="amd.20150915155634.113"><vh>td</vh></v>
<v t="amd.20150915155634.114"><vh>td</vh></v>
<v t="amd.20150915155634.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.116"><vh>h2</vh></v>
<v t="amd.20150915155634.117"><vh>p</vh>
<v t="amd.20150915155634.118"><vh>q</vh></v>
</v>
<v t="amd.20150915155634.119"><vh>blockquote</vh></v>
<v t="amd.20150915155634.120"><vh>h2</vh></v>
<v t="amd.20150915155634.121"><vh>p</vh>
<v t="amd.20150915155634.122"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.123"><vh>h2</vh></v>
<v t="amd.20150915155634.124" a="E"><vh>p</vh>
<v t="amd.20150915155634.125"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.126"><vh>p</vh>
<v t="amd.20150915155634.127"><vh>em</vh></v>
</v>
<v t="amd.20150915155634.128"><vh>h2</vh></v>
<v t="amd.20150915155634.129"><vh>p</vh>
<v t="amd.20150915155634.130"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.131"><vh>iframe</vh></v>
<v t="amd.20150915155634.132"><vh>h2</vh></v>
<v t="amd.20150915155634.133" a="E"><vh>p</vh>
<v t="amd.20150915155634.134"><vh>code</vh></v>
<v t="amd.20150915155634.135"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.136"><vh>h2</vh></v>
<v t="amd.20150915155634.137"><vh>p</vh>
<v t="amd.20150915155634.138"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.139"><vh>pre</vh>
<v t="amd.20150915155634.140"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915155634.142"><vh>p</vh></v>
<v t="amd.20150915155634.143" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915155634.148"><vh>li</vh>
<v t="amd.20150915155634.149"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.150"><vh>li</vh>
<v t="amd.20150915155634.151"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.152"><vh>li</vh>
<v t="amd.20150915155634.153"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.146"><vh>li</vh>
<v t="amd.20150915155634.147"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.145"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915155634.158"><vh>script</vh></v>
<v t="amd.20150915155634.159"><vh>script</vh></v>
<v t="amd.20150915155634.160"><vh>script</vh></v>
</v>
</v>
</v>
<v t="ibm.20150918175403.1"><vh>@clean cpw1.html</vh>
<v t="ibm.20150918175403.2"><vh>檔案說明</vh></v>
<v t="ibm.20150918175403.3"><vh>html 標註</vh>
<v t="ibm.20150918175403.4" a="E"><vh>body 標註</vh>
<v t="ibm.20150918175403.5" a="E"><vh>div class="reveal"</vh>
<v t="ibm.20150918175403.6" a="E"><vh>div class="slides"</vh>
<v t="ibm.20150918175403.7"><vh>有關我的作業</vh></v>
<v t="ibm.20150918175403.8"><vh>課程規劃</vh></v>
<v t="ibm.20150918175403.9"><vh>作業規劃</vh></v>
<v t="ibm.20150918175711.1"><vh>Git 操作</vh></v>
<v t="ibm.20150918175951.1"><vh>Jupyter 操作</vh></v>
<v t="ibm.20150918181528.1"><vh>結論</vh></v>
</v>
</v>
<v t="ibm.20150918175403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915211341.1"><vh>@clean simplest.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1" a="E"><vh>html 標註</vh>
<v t="amd.20150915211351.4" a="E"><vh>body 標註</vh>
<v t="amd.20150915211351.5" a="E"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151019051020.1"><vh>div class="slides"</vh></v>
<v t="amd.20150915211351.7"><vh>有關我的作業</vh></v>
<v t="amd.20150915211351.9"><vh>124週作業心得</vh></v>
<v t="leo.20151019051020.3"><vh>5週作業心得</vh></v>
<v t="leo.20151025235032.1"><vh>6週作業心得</vh></v>
<v t="amd.20150915211351.12"><vh>23週自評</vh></v>
<v t="leo.20151025234541.1"><vh>45週自評</vh></v>
<v t="leo.20151025234826.1"><vh>6週自評</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="harry.20151109111953.1"><vh>@clean simplest3.html</vh>
<v t="harry.20151109111953.2"><vh>檔案說明</vh></v>
<v t="harry.20151109111953.3" a="E"><vh>html 標註</vh>
<v t="harry.20151109111953.4" a="E"><vh>body 標註</vh>
<v t="harry.20151109111953.5" a="E"><vh>div class="reveal"</vh>
<v t="harry.20151109111953.6" a="E"><vh>div class="slides"</vh>
<v t="harry.20151109111953.7"><vh>div class="slides"</vh></v>
<v t="harry.20151109112006.1"><vh>投影片第一頁</vh></v>
<v t="harry.20151109112014.1"><vh>投影片第二頁</vh>
<v t="harry.20151109112014.2"><vh>1</vh></v>
<v t="harry.20151109112014.3"><vh>2</vh></v>
<v t="harry.20151109112014.4"><vh>3</vh></v>
</v>
<v t="harry.20151109112021.1"><vh>第一、二週作業心得</vh></v>
<v t="harry.20151109112030.1"><vh>第一、二週自評</vh></v>
</v>
</v>
<v t="harry.20151109111953.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="harry.20151109112933.1"><vh>@clean simplest4.html</vh>
<v t="harry.20151109112933.2"><vh>檔案說明</vh></v>
<v t="harry.20151109112933.3" a="E"><vh>html 標註</vh>
<v t="harry.20151109112933.4" a="E"><vh>body 標註</vh>
<v t="harry.20151109112933.5" a="E"><vh>div class="reveal"</vh>
<v t="harry.20151109112933.6" a="E"><vh>div class="slides"</vh>
<v t="harry.20151109112933.7"><vh>div class="slides"</vh></v>
<v t="harry.20151109112933.8"><vh>投影片第一頁</vh></v>
<v t="harry.20151109112933.9"><vh>投影片第二頁</vh>
<v t="harry.20151109112933.10"><vh>1</vh></v>
<v t="harry.20151109112933.11"><vh>2</vh></v>
<v t="harry.20151109112933.12"><vh>3</vh></v>
</v>
<v t="harry.20151109112951.1"><vh>第三週作業心得</vh></v>
<v t="harry.20151109112957.1"><vh>第三週自評</vh></v>
</v>
</v>
<v t="harry.20151109112933.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="harry.20151109112421.1"><vh>@clean simplest5.html</vh>
<v t="harry.20151109112421.2"><vh>檔案說明</vh></v>
<v t="harry.20151109112421.3" a="E"><vh>html 標註</vh>
<v t="harry.20151109112421.4" a="E"><vh>body 標註</vh>
<v t="harry.20151109112421.5" a="E"><vh>div class="reveal"</vh>
<v t="harry.20151109112421.6" a="E"><vh>div class="slides"</vh>
<v t="harry.20151109112421.7"><vh>div class="slides"</vh></v>
<v t="harry.20151109112421.8"><vh>投影片第一頁</vh></v>
<v t="harry.20151109112421.9"><vh>投影片第二頁</vh>
<v t="harry.20151109112421.10"><vh>1</vh></v>
<v t="harry.20151109112421.11"><vh>2</vh></v>
<v t="harry.20151109112421.12"><vh>3</vh></v>
</v>
<v t="harry.20151109112731.1"><vh>第四週作業心得</vh></v>
<v t="harry.20151109112739.1"><vh>第四週自評</vh></v>
</v>
</v>
<v t="harry.20151109112421.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="harry.20151109112746.1"><vh>@clean simplest6.html</vh>
<v t="harry.20151109112746.2"><vh>檔案說明</vh></v>
<v t="harry.20151109112746.3" a="E"><vh>html 標註</vh>
<v t="harry.20151109112746.4" a="E"><vh>body 標註</vh>
<v t="harry.20151109112746.5" a="E"><vh>div class="reveal"</vh>
<v t="harry.20151109112746.6" a="E"><vh>div class="slides"</vh>
<v t="harry.20151109112746.7"><vh>div class="slides"</vh></v>
<v t="harry.20151109112746.8"><vh>投影片第一頁</vh></v>
<v t="harry.20151109112746.9"><vh>投影片第二頁</vh>
<v t="harry.20151109112746.10"><vh>1</vh></v>
<v t="harry.20151109112746.11"><vh>2</vh></v>
<v t="harry.20151109112746.12"><vh>3</vh></v>
</v>
<v t="harry.20151109112917.1"><vh>第五週作業心得</vh></v>
<v t="harry.20151109112924.1"><vh>第五週自評</vh></v>
</v>
</v>
<v t="harry.20151109112746.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="harry.20151109112747.1"><vh>@clean simplest7.html</vh>
<v t="harry.20151109112747.2"><vh>檔案說明</vh></v>
<v t="harry.20151109112747.3" a="E"><vh>html 標註</vh>
<v t="harry.20151109112747.4" a="E"><vh>body 標註</vh>
<v t="harry.20151109112747.5" a="E"><vh>div class="reveal"</vh>
<v t="harry.20151109112747.6" a="E"><vh>div class="slides"</vh>
<v t="harry.20151109112747.7"><vh>div class="slides"</vh></v>
<v t="harry.20151109112747.8"><vh>投影片第一頁</vh></v>
<v t="harry.20151109112747.9"><vh>投影片第二頁</vh>
<v t="harry.20151109112747.10"><vh>1</vh></v>
<v t="harry.20151109112747.11"><vh>2</vh></v>
<v t="harry.20151109112747.12"><vh>3</vh></v>
</v>
<v t="harry.20151109113035.1"><vh>第六週作業心得</vh></v>
<v t="harry.20151109113042.1"><vh>第六週自評</vh></v>
</v>
</v>
<v t="harry.20151109112747.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="harry.20151109112749.1"><vh>@clean simplest8.html</vh>
<v t="harry.20151109112749.2"><vh>檔案說明</vh></v>
<v t="harry.20151109112749.3" a="E"><vh>html 標註</vh>
<v t="harry.20151109112749.4" a="E"><vh>body 標註</vh>
<v t="harry.20151109112749.5" a="E"><vh>div class="reveal"</vh>
<v t="harry.20151109112749.6" a="E"><vh>div class="slides"</vh>
<v t="harry.20151109112749.7"><vh>div class="slides"</vh></v>
<v t="harry.20151109112749.8"><vh>投影片第一頁</vh></v>
<v t="harry.20151109112749.9"><vh>投影片第二頁</vh>
<v t="harry.20151109112749.10"><vh>1</vh></v>
<v t="harry.20151109112749.11"><vh>2</vh></v>
<v t="harry.20151109112749.12"><vh>3</vh></v>
</v>
<v t="harry.20151109113053.1"><vh>第七週作業心得</vh></v>
<v t="harry.20151109113057.1"><vh>第七週自評</vh></v>
</v>
</v>
<v t="harry.20151109112749.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033359.1"><vh>@clean simplest10.html</vh>
<v t="123.20160104033359.2"><vh>檔案說明</vh></v>
<v t="123.20160104033359.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033359.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033359.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033359.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033359.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033359.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033359.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033359.10"><vh>1</vh></v>
<v t="123.20160104033359.11"><vh>2</vh></v>
<v t="123.20160104033359.12"><vh>3</vh></v>
</v>
<v t="123.20160104033359.13"><vh>第十週作業心得</vh></v>
<v t="123.20160104033359.14"><vh>第十週自評</vh></v>
</v>
</v>
<v t="123.20160104033359.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033405.1"><vh>@clean simplest11.html</vh>
<v t="123.20160104033405.2"><vh>檔案說明</vh></v>
<v t="123.20160104033405.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033405.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033405.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033405.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033405.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033405.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033405.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033405.10"><vh>1</vh></v>
<v t="123.20160104033405.11"><vh>2</vh></v>
</v>
<v t="123.20160104033405.12"><vh>第十一週作業心得</vh></v>
<v t="123.20160104033405.13"><vh>第十一週自評</vh></v>
</v>
</v>
<v t="123.20160104033405.14"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033409.1"><vh>@clean simplest12.html</vh>
<v t="123.20160104033409.2"><vh>檔案說明</vh></v>
<v t="123.20160104033409.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033409.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033409.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033409.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033409.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033409.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033409.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033409.10"><vh>1</vh></v>
<v t="123.20160104033409.11"><vh>2</vh></v>
<v t="123.20160104033409.12"><vh>3</vh></v>
</v>
<v t="123.20160104033409.13"><vh>第十二週作業心得</vh></v>
<v t="123.20160104033409.14"><vh>第十二週自評</vh></v>
</v>
</v>
<v t="123.20160104033409.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033414.1"><vh>@clean simplest13.html</vh>
<v t="123.20160104033414.2"><vh>檔案說明</vh></v>
<v t="123.20160104033414.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033414.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033414.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033414.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033414.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033414.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033414.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033414.10"><vh>1</vh></v>
<v t="123.20160104033414.11"><vh>2</vh></v>
</v>
<v t="123.20160104033414.12"><vh>第十三週作業心得</vh></v>
<v t="123.20160104033414.13"><vh>第十三週自評</vh></v>
</v>
</v>
<v t="123.20160104033414.14"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033419.1"><vh>@clean simplest14.html</vh>
<v t="123.20160104033419.2"><vh>檔案說明</vh></v>
<v t="123.20160104033419.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033419.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033419.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033419.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033419.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033419.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033419.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033419.10"><vh>1</vh></v>
<v t="123.20160104033419.11"><vh>2</vh></v>
</v>
<v t="123.20160104033419.12"><vh>第十四週作業心得</vh></v>
<v t="123.20160104033419.13"><vh>第十四週自評</vh></v>
</v>
</v>
<v t="123.20160104033419.14"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033423.1"><vh>@clean simplest15.html</vh>
<v t="123.20160104033423.2"><vh>檔案說明</vh></v>
<v t="123.20160104033423.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033423.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033423.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033423.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033423.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033423.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033423.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033423.10"><vh>1</vh></v>
</v>
<v t="123.20160104033423.11"><vh>第十五週作業心得</vh></v>
<v t="123.20160104033423.12"><vh>第十五週自評</vh></v>
</v>
</v>
<v t="123.20160104033423.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160104033428.1"><vh>@clean simplest16.html</vh>
<v t="123.20160104033428.2"><vh>檔案說明</vh></v>
<v t="123.20160104033428.3" a="E"><vh>html 標註</vh>
<v t="123.20160104033428.4" a="E"><vh>body 標註</vh>
<v t="123.20160104033428.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160104033428.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160104033428.7"><vh>div class="slides"</vh></v>
<v t="123.20160104033428.8"><vh>投影片第一頁</vh></v>
<v t="123.20160104033428.9" a="E"><vh>投影片第二頁</vh>
<v t="123.20160104033428.10"><vh>1</vh></v>
<v t="123.20160104033428.11"><vh>2</vh></v>
<v t="123.20160104033428.12"><vh>3</vh></v>
<v t="123.20160104033428.13"><vh>4</vh></v>
<v t="123.20160104033428.14"><vh>5</vh></v>
<v t="123.20160104033428.15"><vh>6</vh></v>
</v>
<v t="123.20160104033428.16"><vh>第十六週自評</vh></v>
</v>
</v>
<v t="123.20160104033428.17"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.1"><vh>@clean v31ref.html</vh>
<v t="amd.20150915170743.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915170743.3" a="E"><vh>head</vh>
<v t="amd.20150915170743.4"><vh>title - 標題</vh></v>
<v t="amd.20150915170743.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915170743.6"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915170743.7" a="E"><vh>body</vh>
<v t="amd.20150915170743.8" a="E"><vh>div - reveal</vh>
<v t="amd.20150915170743.9" a="E"><vh>div - slides</vh>
<v t="amd.20150915170743.10"><vh>h1 - 一般單頁</vh></v>
<v t="amd.20150915170743.11"><vh>h2</vh></v>
<v t="amd.20150915170743.12" a="E"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915170743.13"><vh>h2</vh></v>
<v t="amd.20150915170743.14"><vh>h2</vh></v>
<v t="amd.20150915170743.15"><vh>h2</vh></v>
</v>
<v t="amd.20150915170743.16"><vh>h2</vh></v>
<v t="amd.20150915170743.17"><vh>h2</vh></v>
<v t="amd.20150915170743.18"><vh>h2</vh></v>
<v t="amd.20150915170743.19"><vh>markdown 頁面</vh></v>
<v t="amd.20150915170743.20" a="E"><vh>h2</vh>
<v t="amd.20150915170743.21"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915170743.22" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915170743.23"><vh>h2</vh></v>
<v t="amd.20150915170743.24"><vh>p</vh></v>
<v t="amd.20150915170743.25"><vh>p</vh></v>
<v t="amd.20150915170743.26"><vh>p</vh></v>
<v t="amd.20150915170743.27"><vh>p</vh></v>
<v t="amd.20150915170743.28"><vh>p</vh></v>
<v t="amd.20150915170743.29"><vh>p</vh></v>
<v t="amd.20150915170743.30"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915170743.31"><vh>h2</vh></v>
<v t="amd.20150915170743.32"><vh>p</vh>
<v t="amd.20150915170743.33"><vh>a</vh></v>
<v t="amd.20150915170743.34"><vh>a</vh></v>
<v t="amd.20150915170743.35"><vh>a</vh></v>
<v t="amd.20150915170743.36"><vh>a</vh></v>
<v t="amd.20150915170743.37"><vh>a</vh></v>
<v t="amd.20150915170743.38"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.39"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915170743.40" a="E"><vh>p</vh>
<v t="amd.20150915170743.41"><vh>a</vh></v>
<v t="amd.20150915170743.42"><vh>a</vh></v>
<v t="amd.20150915170743.43"><vh>a</vh></v>
<v t="amd.20150915170743.44"><vh>a</vh></v>
<v t="amd.20150915170743.45"><vh>a</vh></v>
<v t="amd.20150915170743.46"><vh>a</vh></v>
<v t="amd.20150915170743.47"><vh>a</vh></v>
<v t="amd.20150915170743.48"><vh>a</vh></v>
<v t="amd.20150915170743.49"><vh>a</vh></v>
<v t="amd.20150915170743.50"><vh>a</vh></v>
<v t="amd.20150915170743.51"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.52"><vh>h2</vh></v>
<v t="amd.20150915170743.53"><vh>p</vh>
<v t="amd.20150915170743.54"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.55"><vh>a</vh></v>
<v t="amd.20150915170743.56"><vh>h2</vh></v>
<v t="amd.20150915170743.57" a="E"><vh>pre</vh>
<v t="amd.20150915170743.58"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.59"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915170743.60" a="E"><vh>pre</vh>
<v t="amd.20150915170743.61"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.62" a="E"><vh>div</vh>
<v t="amd.20150915170743.63"><vh>h2</vh></v>
<v t="amd.20150915170743.64"><vh>pre</vh>
<v t="amd.20150915170743.65"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915170743.66"><vh>h2</vh></v>
<v t="amd.20150915170743.67"><vh>h2</vh></v>
<v t="amd.20150915170743.68"><vh>p</vh></v>
<v t="amd.20150915170743.69"><vh>pre</vh>
<v t="amd.20150915170743.70"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.71"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915170743.72"><vh>p</vh></v>
<v t="amd.20150915170743.73" a="E"><vh>pre</vh>
<v t="amd.20150915170743.74"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.75" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915170743.76" a="E"><vh>pre</vh>
<v t="amd.20150915170743.77"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.78"><vh>p</vh></v>
</v>
<v t="amd.20150915170743.79"><vh>h2</vh></v>
<v t="amd.20150915170743.80" a="E"><vh>ul</vh>
<v t="amd.20150915170743.81"><vh>li</vh></v>
<v t="amd.20150915170743.82"><vh>li</vh></v>
<v t="amd.20150915170743.83"><vh>li</vh></v>
<v t="amd.20150915170743.84"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.85"><vh>h2</vh></v>
<v t="amd.20150915170743.86"><vh>ol</vh>
<v t="amd.20150915170743.87"><vh>li</vh></v>
<v t="amd.20150915170743.88"><vh>li</vh></v>
<v t="amd.20150915170743.89"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.90"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915170743.91" a="E"><vh>table</vh>
<v t="amd.20150915170743.92"><vh>thead</vh>
<v t="amd.20150915170743.93"><vh>tr</vh>
<v t="amd.20150915170743.94"><vh>th</vh></v>
<v t="amd.20150915170743.95"><vh>th</vh></v>
<v t="amd.20150915170743.96"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915170743.97"><vh>tbody</vh>
<v t="amd.20150915170743.98"><vh>tr</vh>
<v t="amd.20150915170743.99"><vh>td</vh></v>
<v t="amd.20150915170743.100"><vh>td</vh></v>
<v t="amd.20150915170743.101"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.102"><vh>tr</vh>
<v t="amd.20150915170743.103"><vh>td</vh></v>
<v t="amd.20150915170743.104"><vh>td</vh></v>
<v t="amd.20150915170743.105"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.106"><vh>tr</vh>
<v t="amd.20150915170743.107"><vh>td</vh></v>
<v t="amd.20150915170743.108"><vh>td</vh></v>
<v t="amd.20150915170743.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.110"><vh>h2</vh></v>
<v t="amd.20150915170743.111"><vh>p</vh>
<v t="amd.20150915170743.112"><vh>q</vh></v>
</v>
<v t="amd.20150915170743.113"><vh>blockquote</vh></v>
<v t="amd.20150915170743.114"><vh>h2</vh></v>
<v t="amd.20150915170743.115"><vh>p</vh>
<v t="amd.20150915170743.116"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.117"><vh>h2</vh></v>
<v t="amd.20150915170743.118" a="E"><vh>p</vh>
<v t="amd.20150915170743.119"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.120"><vh>p</vh>
<v t="amd.20150915170743.121"><vh>em</vh></v>
</v>
<v t="amd.20150915170743.122"><vh>h2</vh></v>
<v t="amd.20150915170743.123"><vh>p</vh>
<v t="amd.20150915170743.124"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.125"><vh>iframe</vh></v>
<v t="amd.20150915170743.126"><vh>h2</vh></v>
<v t="amd.20150915170743.127" a="E"><vh>p</vh>
<v t="amd.20150915170743.128"><vh>code</vh></v>
<v t="amd.20150915170743.129"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.130"><vh>h2</vh></v>
<v t="amd.20150915170743.131"><vh>p</vh>
<v t="amd.20150915170743.132"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.133"><vh>pre</vh>
<v t="amd.20150915170743.134"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915170743.136"><vh>p</vh></v>
<v t="amd.20150915170743.137" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915170743.138"><vh>li</vh>
<v t="amd.20150915170743.139"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.140"><vh>li</vh>
<v t="amd.20150915170743.141"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.142"><vh>li</vh>
<v t="amd.20150915170743.143"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.144"><vh>li</vh>
<v t="amd.20150915170743.145"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.146"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.147"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915170743.148"><vh>script</vh></v>
<v t="amd.20150915170743.149"><vh>script</vh></v>
<v t="amd.20150915170743.150"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151005101111.1"><vh>Recovered Nodes</vh>
<v t="leo.20151005101111.2"><vh>Recovered node "html 標註" from @clean simplest.html</vh>
<v t="leo.20151005101111.3"><vh>old:html 標註</vh></v>
<v t="leo.20151005101111.4"><vh>new:html 標註</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="123.20160104033359.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033359.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) http://conda.pydata.org/miniconda.html &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) python3.5 (64bit) &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3)conda install pip &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033359.11">&lt;section&gt;
    &lt;p align="left"&gt;(4)pip install pelican Markdown &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(5)conda install pyqt &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(6)pip install  &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(7)conda install anaconda-client &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
</t>
<t tx="123.20160104033359.12">&lt;section&gt;

    &lt;p align="left"&gt;(8)conda install jupyter &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160104033359.13">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第十週作業心得&lt;/h2&gt;
    &lt;p&gt;之前的使用工具都是由老師提供給我們的，可是工具的版本會不斷的更新，因此我們不能只依賴老師提供新版本給我們，要自己學習如何更新工具的版本，學會自主管理。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033359.14">&lt;section&gt;
    &lt;h2&gt;第十週成績自評&lt;/h2&gt;
    &lt;p&gt;第十週的課程在於讓我們自己學會打理自己使用的工具，工具會時時刻刻的更新版本，我們也要學會同步更新版本，這樣才能夠跟著時代的潮流，使用最新的工具，建立我們的專業能力，在課程上，雖然看起來操作簡單，但是其實還滿佈好弄得，有時候還會按錯，很難發現，不過在同學的幫助下還是有成功。所以我給自己65分。
    
    評分：65
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033359.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033359.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033359.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033359.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033359.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033359.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033359.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033359.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033359.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="123.20160104033405.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033405.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) 進入班級倉儲gihhub網頁&lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) 進入分支頁面(gh-pages) &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3) 到commit尋找個人倉儲path尚未刪除時的版本 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033405.11">&lt;section&gt;
    &lt;p align="left"&gt;(4)複製版本碼 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(5)到cmd介面 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(6)輸入gitreset-hard版本碼  &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(7)將舊版內自己的另存至user的資料夾 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
</t>
<t tx="123.20160104033405.12">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第十一週作業心得&lt;/h2&gt;
    &lt;p&gt;這週課程，因為老師將user節點刪除了，所以我們如果要更新自己的檔案，必須再回到舊版本的倉儲，進行下載，然後再另存至自己的user裡面，才能再度進行個人倉儲的更動。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033405.13">&lt;section&gt;
    &lt;h2&gt;第十一週成績自評&lt;/h2&gt;
    &lt;p&gt;在這週需要將自己的倉儲leo從舊版本的班上倉儲複製到自己的user資料夾裡，但是因為複製的過程中，會有網址及路徑的衝突，如果沒有處理好的話就沒辦法產生資料，在這方面處理了有點久。所以我給自己70分。
    
    評分：70
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033405.14">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033405.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033405.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033405.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033405.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033405.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033405.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033405.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033405.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="123.20160104033409.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033409.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) 至 Leo-editor GitHub&lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) 到 releases 找最新的zip檔 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3)將檔案拉到 Ana3_2015 的 data &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033409.11">&lt;section&gt;
    &lt;p align="left"&gt;(4)下載 fix壓縮檔並且壓縮後拉到Ana3_2015 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(5)下載leo壓縮檔，並放在fix資料夾 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(6)新增fix路徑 copy leo-editor-broke-abbrev.zip  &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(7) 更改start的pip install leo-editor-broke-abbrev.zip &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
</t>
<t tx="123.20160104033409.12">&lt;section&gt;

    &lt;p align="left"&gt;(8)啟用fix ，將檔案複製到指定位置即可 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160104033409.13">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第十二週作業心得&lt;/h2&gt;
    &lt;p&gt;這週修改了fix檔內路徑，並且更新了leo5.1的版本，實際上更新並不難，但是在操作過程中很容易出現bug，導致某些地方的網址或者資料沒有更動到，然後就全部都不能更新，所以在過程中需要一步一步謹慎的處理。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033409.14">&lt;section&gt;
    &lt;h2&gt;第十二週成績自評&lt;/h2&gt;
    &lt;p&gt;這,週的作業在課堂上跟同學們一起完成了，後來在私下時間有再度更新過，但是似乎因為版次有所不同，導致更新沒有成功，不過在隨身碟當中的leo是已經更新完成了，所以目前使用都沒有問題。所以我給自己70分。
    
    評分：70
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033409.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033409.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033409.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033409.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033409.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033409.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033409.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033409.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033409.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="123.20160104033414.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033414.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) 便利的使用網路資源進行資料傳輸 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) 能使用英文零件圖進行繪製 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3)完成零件圖的繪製以及組立 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033414.11">&lt;section&gt;
    &lt;p align="left"&gt;(4)利用錄影表達自己的繪圖能力 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(5)同學間能夠互相觀看影片學習繪圖方式 &lt;/p&gt;
    &lt;br&gt;

&lt;/section&gt;
</t>
<t tx="123.20160104033414.12">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第十三週作業心得&lt;/h2&gt;
    &lt;p&gt;這週是擅長的繪圖課程，不過因為使用的軟體不是很熟悉，所以在繪圖過程上花了不少，可是組內的每位同學都很配合，在零件繪製上面會互相幫助，所以在這週的進度上，得以迅速完成。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033414.13">&lt;section&gt;
    &lt;h2&gt;第十三週成績自評&lt;/h2&gt;
    &lt;p&gt;在這週的繪圖課程哩，要在每個組員間分配工作，在這點上面我們的組長做得很好，他有好好的分配每個人的工作，讓大家都有適合的工作量，組員間不懂的事情他也都會幫助大家，相對之下我自己在上課的時候理解的很少，但是仍然會試著解決我所遇到的問題。所以我給自己65分。
    
    評分：65
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033414.14">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033414.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033414.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033414.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033414.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033414.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033414.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033414.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033414.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="123.20160104033419.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033419.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) Creo可另存零件為stl檔 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) stl檔上傳到github &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3)在github會顯示立體圖 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033419.11">&lt;section&gt;
    &lt;p align="left"&gt;(4)github有一個raw鍵 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(5)複製網址 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(6)使用老師課程中的語法  &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(7)在網頁上就能顯示360度零件圖 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
</t>
<t tx="123.20160104033419.12">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第十四週作業心得&lt;/h2&gt;
    &lt;p&gt;老師在課堂上的講解很清楚，在這次的課程中，很快就能將零件以360度的方式呈現在網頁中，不過在儲存零件時，有一點要特別注意，如果沒有存成ASCII檔，會沒辦法正確呈現。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033419.13">&lt;section&gt;
    &lt;h2&gt;第十四週成績自評&lt;/h2&gt;
    &lt;p&gt;這周的課程相對起來比較簡單，而且老師在課程上講的也很清楚，所以進度相當快，我也利用了剩下的時間繪製其餘零件。所以我給自己70分。
    
    評分：70
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033419.14">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033419.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033419.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033419.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033419.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033419.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033419.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033419.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033419.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="123.20160104033423.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033423.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) 建立工作空間"cadpb_g2_nutcracker" &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) 使用share功能分享給組員並設定權限 &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3)組員在工作空間中要先點選Create assembly建立自己的組立空間 &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033423.11">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第十五週作業心得&lt;/h2&gt;
    &lt;p&gt;這週的作業要組內的組員們一起完成，一開始大家不斷的傳送零件到空間中，導致空間會當機，變得很lag，後來統一將零件由一個人傳送上去，大家再各自進行組立，就很順利了，Onshape是很不錯的網頁空間，可以在網頁上組立，而且功能也相當齊全。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033423.12">&lt;section&gt;
    &lt;h2&gt;第十五週成績自評&lt;/h2&gt;
    &lt;p&gt;這週的進度是組別的進度，要組內的大家一起完成，在過程中比較困難的是約束的部分，因為約束有時候不知道要填入哪個約束才能完整的約束好，不會有干涉，除此之外並不難，也在課堂上就完成了。所以我給自己65分。
    
    評分：65
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033423.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033423.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033423.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033423.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033423.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033423.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033423.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033423.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033423.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="123.20160104033428.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160104033428.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="123.20160104033428.11">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="123.20160104033428.12">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033428.13">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p align="left"&gt;(1) http://conda.pydata.org/miniconda.html &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(2) python3.5 (64bit) &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(3)conda install pip &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
	
</t>
<t tx="123.20160104033428.14">&lt;section&gt;
    &lt;p align="left"&gt;(4)pip install pelican Markdown &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(5)conda install pyqt &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(6)pip install  &lt;/p&gt;
    &lt;br&gt;
    &lt;p align="left"&gt;(7)conda install anaconda-client &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
</t>
<t tx="123.20160104033428.15">&lt;section&gt;

    &lt;p align="left"&gt;(8)conda install jupyter &lt;/p&gt;
    &lt;br&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160104033428.16">&lt;section&gt;
    &lt;h2&gt;第十六週成績自評&lt;/h2&gt;
    &lt;p&gt;總結了這個學期的一些筆記，在課程中也學習了許多不同的東西，尤其是新穎的軟體以及程式，讓我對科技的演變更加欽佩，老師教的製圖軟體在方便性上真的相當強大，尤其是可以帶著跑的creo以及網頁中就能組立的Onshape等等，在這些課堂上我也學到不少，不過常常不能馬上學以致用，但是仍然會試著學習。所以我給自己65分。
    
    評分：65
    
    
&lt;/section&gt;
				
</t>
<t tx="123.20160104033428.17">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160104033428.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160104033428.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160104033428.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160104033428.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033428.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033428.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160104033428.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="123.20160104033428.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150913233943.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20150913233943.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150913233943.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="amd.20150913233943.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="amd.20150913233943.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150913233943.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.81">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="amd.20150913233943.82">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="amd.20150913233943.83">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="amd.20150913234947.1">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150913235034.1">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="amd.20150913235123.1">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="amd.20150913235225.1">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="amd.20150914000138.1">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150914000332.1">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150914000332.2">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="amd.20150915153206.1">2015.09.15

將 2014 的 index.html 與 cadpbw1.html 與 2015 最新的 reveal 框架檔案合併
此後將以 v31ref.html 中的語法為主

</t>
<t tx="amd.20150915155634.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915155634.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915155634.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915155634.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915155634.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915155634.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915155634.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915155634.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915155634.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915155634.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915155634.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915155634.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915155634.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915155634.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915155634.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915155634.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915155634.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915155634.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915155634.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915155634.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915155634.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915155634.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915155634.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.145">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915155634.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.147">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915155634.148">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.149">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915155634.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.151">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915155634.152">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.153">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915155634.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915155634.158">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915155634.159">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915155634.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.160">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915155634.17">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.18">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.19">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915155634.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.21">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.29">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915155634.30">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.31">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.32">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.33">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.34">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.35">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915155634.36">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.37">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.38">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.39">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="amd.20150915155634.40">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.41">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.42">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.43">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.44">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.45">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915155634.46">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.47">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915155634.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915155634.52">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.57">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.58">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.59">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915155634.60">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915155634.61">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.62">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.63">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.64">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.65">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915155634.66">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915155634.67">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.68">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915155634.69">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915155634.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915155634.70">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.71">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.72">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.73">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.74">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915155634.75">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915155634.76">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.77">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.78">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.79">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915155634.80">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.81">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915155634.82">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915155634.83">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915155634.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915155634.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915155634.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915155634.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915155634.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915160450.1">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915161424.1">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915170743.10">&lt;section&gt;
        &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915170743.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915170743.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915170743.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915170743.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915170743.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.110">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.111">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.112">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915170743.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.114">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.115">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915170743.116">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915170743.117">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.118">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.119">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915170743.12">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.120">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.121">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915170743.122">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.123">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.124">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915170743.125">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.126">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.127">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.128">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915170743.129">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915170743.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.130">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.131">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.132">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915170743.133">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.134">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915170743.135">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.136">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915170743.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915170743.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915170743.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915170743.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915170743.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915170743.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915170743.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915170743.149">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915170743.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.150">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915170743.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.17">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.18">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915170743.20">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.21">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915170743.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915170743.31">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.32">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.33">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915170743.34">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.35">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.36">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.37">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.38">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915170743.39">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;reveal.js - The HTML Presentation Framework&lt;/title&gt;

</t>
<t tx="amd.20150915170743.40">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915170743.41">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915170743.42">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.43">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.44">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.45">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.46">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915170743.47">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.5">&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="Hakim El Hattab"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915170743.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915170743.52">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.53">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.54">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915170743.55">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915170743.56">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.57">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.58">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.6">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915170743.60">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915170743.61">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915170743.62">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.63">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915170743.64">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915170743.65">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.66">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.67">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.68">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.69">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915170743.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915170743.70">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915170743.71">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.72">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.73">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.74">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915170743.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915170743.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915170743.79">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.8">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915170743.80">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.81">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915170743.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.85">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.86">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915170743.87">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915170743.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.9">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915170743.90">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.91">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915170743.93">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.94">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915170743.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915170743.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915170743.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915170743.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915172241.1">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915173703.1">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915173703.2">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915173703.3">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915173703.4">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915204710.1">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
    &lt;h2&gt;第二、三週成績自評&lt;/h2&gt;
    &lt;p&gt;第3周並沒有在限定時間內完成作業，而是後來才補交作業的，所以我給自己60分 。

&lt;/section&gt;
				
</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    &lt;p&gt;40323251 雷堯軒 2015/10/05&lt;/p&gt;
    &lt;p&gt;第四週作業更新於2015/10/11&lt;/p&gt;	
    &lt;p&gt;第五週作業更新於2015/10/19&lt;/p&gt;
    &lt;p&gt;第六週作業更新於2015/10/25&lt;/p&gt;	
&lt;/section&gt;
	
</t>
<t tx="amd.20150915211351.9">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第一、二週作業心得&lt;/h2&gt;
    &lt;p&gt;對於程式這方面不太熟悉，對於老師教的也沒有很了解再加上上課都沒有很專心，作業都是拜託同學教導我才懂得，以後還是會盡力學習。&lt;/p&gt;
    &lt;p&gt;筆記:分支 git branch (名稱)
    選擇分支 git checkout (名稱)
    
    
    
    &lt;p&gt;第四週作業心得--這次使用的是SolveSpace繪圖軟體，使用上感覺比proe好用，應該是一個很不錯的繪圖軟體，不過因為英文介面會看不懂，所以可能需要加強一下英文能力。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102209.1">本專案

利用 Jupyter 產生 IPython notebook, 然後整合入 pelican 網誌

利用 github pages 在 github.io 網站上伺服網頁資料

利用 reveal.js 產生投影片

利用 pelican 與 Markdown 產生網誌文章

利用 disqus 建立互動留言系統</t>
<t tx="amd.20150919102541.1">在 Anaconda 3 中只要

    pip install pelican Markdown 

安裝 pelican 與 Markdown Python 模組即可

若是在 Ubuntu 中則可以透過

    sudo pip3 install pelican Markdown 

安裝 pelican 與 Markdown Python 模組</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103341.1">REM start.bat 中 取電腦 IP 與 Jupyter 啟動

REM 取 IPV4 IP address
for /f "delims=[] tokens=2" %%a in ('ping -4 %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 取 IPV6 IP address
REM for /f "delims=[] tokens=2" %%a in ('ping %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 啟動 Jupyter
cd notebook
start %Disk%:\Anaconda3\python.exe "%Disk%:\Anaconda3\Scripts\ipython-script.py" notebook --ip=%thisip% --certfile=%Disk%:\home\ssl_cert.pem --profile=nbserver</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919103428.1"></t>
<t tx="amd.20150919103923.1">home/.ipython/profile_nbserver/ipython_notebook_config.py

內容為:

# Password to use for web authentication
c = get_config()
# password is  "2015cp"
c.NotebookApp.password = u'sha1:864c0bcdb94e:8a396ef692ef3cc552177f1b1c48cec70c7a32df'
c.NotebookApp.port = 8888

產生 password 的程式碼:

from IPython.lib import passwd
passwd()

</t>
<t tx="amd.20150919104249.1">@language python
# show 出 ipython notebook 所使用的 profile 目錄
# 這裡應該會傳回 {'location': 'y:\\home\\.ipython\\profile_nbserver'}
# 表示 custom.js 位於 'y:\\home\\.ipython\\profile_nbserver\\static\\custom'
'''在 custom.js 中加入
require(["base/js/events"], function (events) {
    events.on("app_initialized.NotebookApp", function () {
    /* load your extension here */
    IPython.load_extensions('read-only');
    });
});
就可以自動導入'y:\\home\\.ipython\\nbextensions\read-only.js' 延伸檔案
read-only toggle 為 Alt+R
'''
# 以下為操作方法
'''當使用者選擇某一 cell, 然後按下 Alt+R, 則 cell 內原本為灰色將會變成白色, 表示
cell 為 read only
''''''
import IPython
ip=IPython.get_ipython()
ip.config.ProfileDir </t>
<t tx="amd.20150919112415.1">使用 Vimeo</t>
<t tx="amd.20150919112710.1"></t>
<t tx="amd.20150919113340.1"></t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
os.system('''pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-bootstrap3
''')
g.es("pelican 執行完畢")</t>
<t tx="harry.20151109111953.1">@language xml
@tabwidth -4
@others

</t>
<t tx="harry.20151109111953.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="harry.20151109111953.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="harry.20151109111953.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="harry.20151109111953.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="harry.20151109111953.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109111953.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109111953.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112006.1">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112014.1">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="harry.20151109112014.2">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112014.3">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="harry.20151109112014.4">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112021.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第一、二週作業心得&lt;/h2&gt;
    &lt;p&gt;對於程式這方面不太熟悉，對於老師教的也沒有很了解再加上上課都沒有很專心，作業都是拜託同學教導我才懂得，以後還是會盡力學習。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112030.1">&lt;section&gt;
    &lt;h2&gt;第一、二週成績自評&lt;/h2&gt;
    &lt;p&gt;有試著在倉儲上建立分支，但是因為一直無法成功，所以後來到學校才請教同學，並不算在限定時間內完成進度，而是後來彌補的，所以我給自己60分 。

&lt;/section&gt;
				
</t>
<t tx="harry.20151109112421.1">@language xml
@tabwidth -4
@others

</t>
<t tx="harry.20151109112421.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112421.11">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="harry.20151109112421.12">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112421.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="harry.20151109112421.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="harry.20151109112421.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="harry.20151109112421.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="harry.20151109112421.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112421.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112421.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112421.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112421.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="harry.20151109112731.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第四週作業心得&lt;/h2&gt;
    
    &lt;p&gt;第四週作業心得--這次使用的是SolveSpace繪圖軟體，使用上感覺比proe好用，應該是一個很不錯的繪圖軟體，不過因為英文介面會看不懂，所以可能需要加強一下英文能力。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112739.1">&lt;section&gt;
    &lt;h2&gt;第四週成績自評&lt;/h2&gt;
    &lt;p&gt;在第四週的功課我很用心在完成，並且也在其中獲得許多知識，更在其中發現滿喜歡使用leo的，因為真的非常方便，用來排版網頁也很容易，滿好上手的。
    並且在作業中也繳交了截圖，以證明我的成績量化依據，也方便老師用來評分。所以我給自己70分。
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112746.1">@language xml
@tabwidth -4
@others

</t>
<t tx="harry.20151109112746.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112746.11">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="harry.20151109112746.12">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112746.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="harry.20151109112746.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="harry.20151109112746.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="harry.20151109112746.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="harry.20151109112746.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112746.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112746.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112746.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112746.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="harry.20151109112747.1">@language xml
@tabwidth -4
@others

</t>
<t tx="harry.20151109112747.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112747.11">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="harry.20151109112747.12">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112747.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="harry.20151109112747.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="harry.20151109112747.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="harry.20151109112747.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="harry.20151109112747.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112747.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112747.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112747.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112747.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="harry.20151109112749.1">@language xml
@tabwidth -4
@others

</t>
<t tx="harry.20151109112749.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112749.11">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="harry.20151109112749.12">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112749.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="harry.20151109112749.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="harry.20151109112749.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="harry.20151109112749.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="harry.20151109112749.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112749.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112749.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112749.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112749.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="harry.20151109112917.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第五週作業心得&lt;/h2&gt;
    &lt;p&gt;Creo_Parametric 2.0這個軟體其實就是pro e 只是因為在今年被Creo公司合併了才改名，在這套軟體當中，可以發現跟其他繪圖軟體相似許多的地方，基本上操作模式大同小異，不過令我感到最大的方便之處在於，組合圖中的零件與零件相配合時，軟體內建有自動功能，所以並不需要特別點選使用什麼約束，而是軟體自動幫我判定，這一大優點讓我覺得pro e是個滿有效率的軟體。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112924.1">&lt;section&gt;
    &lt;h2&gt;第五週成績自評&lt;/h2&gt;
    &lt;p&gt;在第五週的功課我很用心在完成，並且也在其中獲得許多知識，為了這次作業而熬夜錄製影片，其中因為不熟悉操作，也直接詢問其他學長怎麼使用，最後也將作業做完，錄製好三個影片。
    並且在作業中繳交了影片，以證明我的成績依據，也方便用來當作評分依據。所以我給自己75分。
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112933.1">@language xml
@tabwidth -4
@others

</t>
<t tx="harry.20151109112933.10">&lt;section&gt;
    &lt;h3&gt;筆記&lt;/h3&gt;
    
    &lt;p&gt;(1)由於學校電腦內部的資料夾少了leo的檔案，所以要去老師網站上2GB的環境載點裡面把leo的檔案複製到缺少的資料夾，然後要透過環境修改start的內容，才可以在開始環境的同時開始leo。&lt;/p&gt;
    
    &lt;p&gt;(2)檢查目前擁有的分支：git branch
    建立新的分支：git branch 新分支的名字
    切換到另外的分支：git branch 另外分支的名字&lt;/p&gt;
    
    &lt;p&gt;(3)切換分支過後，資料夾的內容會同步改變。&lt;/p&gt;
    
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112933.11">&lt;section&gt;
    &lt;p&gt;(4)回推分支內容時，要輸入"git push gh-pages"才會成功回推到分支。&lt;/p&gt;
    
    &lt;p&gt;(5)如果不輸入"git push gh-pages"會重複出現錯誤，而且會無法回推成功。&lt;/p&gt;
    
    &lt;p&gt;(6)Solvespace基本操作手冊在老師的網頁上有顯示，基本上按照手冊上的操作就可以了。&lt;/p&gt;
    
    &lt;p&gt;(7)另外，Solvespace的檔案在data資料夾的apps裡面，如果裡面沒有檔案，要到電腦教室裡面的資料夾複製。&lt;/p&gt;
    
&lt;/section&gt;
</t>
<t tx="harry.20151109112933.12">&lt;section&gt;

    &lt;p&gt;(8)新的分支頁面，在創立的同時會複製主頁面的檔案。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112933.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="harry.20151109112933.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="harry.20151109112933.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="harry.20151109112933.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="harry.20151109112933.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112933.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112933.7">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="harry.20151109112933.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;電腦輔助機械設計&lt;/h2&gt;
    
    &lt;h3&gt;40323251 雷堯軒&lt;h3&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="harry.20151109112933.9">&lt;section&gt;
&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;
				
</t>
<t tx="harry.20151109112951.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第三週作業心得&lt;/h2&gt;
    
    &lt;p&gt;第三週作業心得--這次在回推分支的內容時，一直鬼打牆，完全回推不上去，原本也確認過已經是在分支的資料夾頁面下了，不過使用"git push"還是無法回推成功，頻頻失敗，不過後來跟同學請教過後，發現要使用"git push gh-pages"才能成功回推到分支頁，不然就會失敗。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109112957.1">&lt;section&gt;
    &lt;h2&gt;第三週成績自評&lt;/h2&gt;
    
    &lt;p&gt;一開始因為指令輸入錯誤，導致內容完全回推不回去，甚至還會蓋掉別的地方的內容，所以到後來有點呈現放棄狀態，在繳交作業前一晚才請教同學，臨時抱佛腳想要解決，幸好後來同學教的方法有成功，不然這次作業就沒有任何成果了。雖然做的不是很好，不過還是有學到東西，所以我給自己70分。

&lt;/section&gt;
				
</t>
<t tx="harry.20151109113035.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第六週作業心得&lt;/h2&gt;
    &lt;p&gt;在第六週的練習裡，我發現了Creo_Parametric 2.0這個軟體更為強大的功能，經過上網搜尋以後發現，原來已經出了3.0版本的Creo，其中可用3.0版本將繪製的圖檔輸出成SolidWorks可以使用的檔案，這項功能使Creo受到更多人的喜愛，不僅原本就已經受到滿多企業的青睞，現在也正隨著需求演變而進化！
    不過我還是對Creo的操作不太熟悉，可能還需要多花點心思在操作介面上，常常要找一個功能找很久，在繪製的效率上面不是很好，會盡力學習。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109113042.1">&lt;section&gt;
    &lt;h2&gt;第六週成績自評&lt;/h2&gt;
    &lt;p&gt;第六週作業要繳交部分腳踏車零件的"2D繪圖、2D機構模擬、3D零組件繪圖、BOM工程圖"，不過因為我們組的進度比較慢一點，在實物測繪上面還沒有什麼成果，再加上期中考快到了，大家也正在面對課業壓力，不過仍然會努力利用課餘時間繪製腳踏車零件，努力學習程式以及完成老師所交代的作業。
    另外在推送作業時，好像有人push時沒有pull導致某些同學的資料消失了，這個部分也要多加注意，自己的資料內容也要輩分一下，以免發生意外。
    
    評分：80
    
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109113053.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第七周作業心得&lt;/h2&gt;
    &lt;p&gt;有關老師課堂上給予我們的solvespace和creo這兩個軟體，由於檔案大小的確不大，所以功能上仍然輸給SoildWork、AutoCAD、Inventor這些軟體，但是solvespace可以隨身攜帶相當方便，如果突然需要使用繪圖軟體的時候，就可以直接拿出來用了，擁有繪圖的最基本功能且在繪圖上也不算難用，只可惜跟其他繪圖軟體的檔案相容性還需要改善
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="harry.20151109113057.1">&lt;section&gt;
    &lt;h2&gt;第七週成績自評&lt;/h2&gt;
    &lt;p&gt;第七週作業也是要繳交部分腳踏車零件的"2D繪圖、2D機構模擬、3D零組件繪圖、BOM工程圖"，目前開始已經有人再把檔案傳送到班級倉儲了，我們這組的進度還需要加強，不過因為在推送作業時，常常有人push時沒有pull導致有些資料消失了，所以現在常常出問題，雖然班上依靠著偉志再補救這些檔案，可是偉志最近好像也很忙，我們自己也要努力不能隨便弄錯步驟，導致倉儲的負擔了。
    
    評分：80
    
    
&lt;/section&gt;
				
</t>
<t tx="ibm.20150918175403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="ibm.20150918175403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="ibm.20150918175403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="ibm.20150918175403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="ibm.20150918175403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="ibm.20150918175403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="ibm.20150918175403.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175403.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175711.1">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918175951.1">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918181528.1">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="leo.20151005101111.1"></t>
<t tx="leo.20151005101111.2">(uncached) amd.20150915211351.1
Diff...
  &lt;!doctype html&gt;
  &lt;html lang="en"&gt;
  &lt;head&gt;
  &lt;meta charset="utf-8"&gt;
  &lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
  &lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
  	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
  	&lt;!--增加對於 IE 早期版本的支援 --&gt;
  	&lt;!--[if lt IE 9]&gt;
  	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
  	&lt;![endif]--&gt;
  &lt;/head&gt;
+ &lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
+ &lt;/html&gt;
+ &gt;&gt;&gt;&gt;&gt;&gt;&gt; 1365161e5ee1a3e979d94ab7def658cb9564abe7
  @others
</t>
<t tx="leo.20151005101111.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
&lt;/html&gt;
&gt;&gt;&gt;&gt;&gt;&gt;&gt; 1365161e5ee1a3e979d94ab7def658cb9564abe7
@others
</t>
<t tx="leo.20151005101111.4">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151019051020.1">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151019051020.3">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第五周作業心得&lt;/h2&gt;
    &lt;p&gt;Creo_Parametric 2.0這個軟體其實就是pro e 只是因為在今年被Creo公司合併了才改名，在這套軟體當中，可以發現跟其他繪圖軟體相似許多的地方，基本上操作模式大同小異，不過令我感到最大的方便之處在於，組合圖中的零件與零件相配合時，軟體內建有自動功能，所以並不需要特別點選使用什麼約束，而是軟體自動幫我判定，這一大優點讓我覺得pro e是個滿有效率的軟體。&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="leo.20151025234541.1">&lt;section&gt;
    &lt;h2&gt;第四、五週成績自評&lt;/h2&gt;
    &lt;p&gt;在第4周與第5周的功課我都很用心在完成，並且也在其中獲得許多知識，更在其中發現滿喜歡使用leo的，因為真的非常方便，用來排版網頁也很容易，滿好上手的。
    並且在作業中也繳交了截圖與影片，以證明我的成績量化依據，也方便老師用來評分。所以想把分數提高到70分。
&lt;/section&gt;
				
</t>
<t tx="leo.20151025234826.1">&lt;section&gt;
    &lt;h2&gt;第六週成績自評&lt;/h2&gt;
    &lt;p&gt;第6週作業要繳交部分腳踏車零件的"2D繪圖、2D機構模擬、3D零組件繪圖、BOM工程圖"，不過因為我們組的進度比較慢一點，在實物測繪上面還沒有什麼成果，再加上期中考快到了，大家也正在面對課業壓力，不過仍然會努力利用課餘時間繪製腳踏車零件，努力學習程式以及完成老師所交代的作業。
    另外在推送作業時，好像有人push時沒有pull導致某些同學的資料消失了，這個部分也要多加注意，自己的資料內容也要輩分一下，以免發生意外。
    
    評分：70
    
    
&lt;/section&gt;
				
</t>
<t tx="leo.20151025235032.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;第六周作業心得&lt;/h2&gt;
    &lt;p&gt;在第六週的練習裡，我發現了Creo_Parametric 2.0這個軟體更為強大的功能，經過上網搜尋以後發現，原來已經出了3.0版本的Creo，其中可用3.0版本將繪製的圖檔輸出成SolidWorks可以使用的檔案，這項功能使Creo受到更多人的喜愛，不僅原本就已經受到滿多企業的青睞，現在也正隨著需求演變而進化！
    不過我還是對Creo的操作不太熟悉，可能還需要多花點心思在操作介面上，常常要找一個功能找很久，在繪製的效率上面不是很好，會盡力學習。
    &lt;/p&gt;
    
&lt;/section&gt;
				
</t>
</tnodes>
</leo_file>
